[package]
name = "image-size-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
clap = { version = "4.3.19", features = ["derive"] }
wax = "0.6.0"
